version: 1.0.{build}
build:
  verbosity: minimal
  
 
install:
  - 'C:\Program Files\Microsoft Visual Studio 14.0\VC\vcvarsall.bat' x86
  - git clone git://code.qt.io/qt/qt5.git
  - cd qt5
  - git checkout 5.6
  - perl init-repository
  - configure.bat -prefix c:\qt-5.6.0-static -opensource -release -static -static-runtime -nomake tests -no-compile-examples -no-opengl -skip serialport -no-qml-debug -no-iconv -skip qtwebkit -skip qtwebkit-examples -skip qtwebengine -skip qtdeclarative 


build_script:
  - nmake
  - nmake install
  
