os: Visual Studio 2015

version: 1.0.{build}
build:
  verbosity: minimal
  
environment:
  QMAKESPEC: win32-msvc2015
 
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
  #'"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - dir
  - git clone git://code.qt.io/qt/qt5.git
  - cd qt5
  - git checkout 5.6
  - perl init-repository
  - configure.bat -prefix c:\qt-5.6.0-static -opensource -release -static -static-runtime -nomake tests -no-compile-examples -no-opengl -skip serialport -no-qml-debug -no-iconv -opensource -confirm-license -skip qtwebkit -skip qtwebkit-examples -skip qtwebengine -skip qtdeclarative -skip location -skip webchannel -skip websockets -skip webview -skip winextras -skip sensors -skip androidextras


build_script:
  #- nmake
  #- nmake install
  - 7z a configured.zip C:\projects\appveyor-qt5-6-static
  - dir configured.zip

artifact:
  - path: configured.zip

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))